#!/bin/bash
#SBATCH --export=ALL #export all enviroment variables to the batch job
#SBATCH -p mrcq #select partition
#SBATCH --time=24:00:00 ##maximum wall time for the job
#SBATCH -A Research_Project-MRC190311 #research project to submit under
#SBATCH --nodes=1 #specify number of nodes
#SBATCH --ntasks-per-node=16 # specify number of processors per node
#SBATCH --mail-type=END # send email at job completion
#SBATCH --error=Visual2_%j.err # error file
#SBATCH --output=Visual2_%j.log # output file
#SBATCH --job-name=Peak_Visual2

source /lustre/home/lm1035/miniconda3/etc/profile.d/conda.sh

conda activate deeptools_env

grep -E "^chr[0-9XY]+\s" mm39_TSS.bed > mm39_TSS_filtered.bed

export TMPDIR=/lustre/projects/Research_Project-T111004/Lachlan/tmp
mkdir -p $TMPDIR

# Paths
BIGWIG_DIR="/lustre/projects/Research_Project-T111004/Lachlan/Project_11657/Peak_Calling/Peaks"
OUTPUT_DIR="/lustre/projects/Research_Project-T111004/Lachlan/Project_11657/Normalise/Peak_Visuals"
TSS_BED="/lustre/projects/Research_Project-T111004/Lachlan/Project_11657/Normalise/mm39_TSS_filtered.bed"

mkdir -p "$OUTPUT_DIR"

# Make a computeMatrix file from all BigWigs
computeMatrix reference-point \
  -S $BIGWIG_DIR/*.bw \
  -R $TSS_BED \
  --referencePoint TSS \
  -a 1500 -b 1500 \
  --skipZeros \
  --sortRegions descend \
  -out $OUTPUT_DIR/tss_matrix.gz \
  --outFileNameMatrix $OUTPUT_DIR/tss_signal_matrix.tab \
  --numberOfProcessors 4

# Plot average profile
plotProfile -m $OUTPUT_DIR/tss_matrix.gz \
  -out $OUTPUT_DIR/tss_profile.png \
  --perGroup \
  --plotTitle "ChIPmentation Signal around TSS (±1.5kb)"

# Plot heatmap
plotHeatmap -m $OUTPUT_DIR/tss_matrix.gz \
  -out $OUTPUT_DIR/tss_heatmap.png \
  --plotTitle "TSS Enrichment Heatmap"
